#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development:
  adapter: postgresql
  database: fantasyfooty
  username: ubuntu
  password: password
  host: localhost

production:
  adapter: postgresql
  database: fantasyfooty
  pool: 5
  timeout: 5000